### ISSUE TITLE
Enable segwit support in wallet and for registering names

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1076]

**Comment by john-light** [comment]
+1 for bech32 P2WPKH native segwit address support.

**Comment by john-light** [comment]
@markmhx why is this issue closed?

**Comment by markmhx** [comment]
I'm closing out a lot of older Blockstack Browser issues since PBC is no longer planning to extend the product's functionality in light of [the general release of Blockstack Connect](https://blog.blockstack.org/upgrade-your-app-onboarding-experience-with-blockstack-connect/). 

I'd recommend creating issues in the https://github.com/blockstack/ux repository if you'd like us to continue consider new functionality for Blockstack Connect or the Blockstack App / new authenticator (improvements to both of which are tracked in that repo). 

However, we haven't yet integrated comprehensive wallet and name registration support into the new authenticator, so I imagine this issue won't be particularly relevant again until we do. In any case, I'm open to hearing more about your interest here so I can better evaluate how they might factor into our plans!
