### ISSUE TITLE
Wallet: Cannot send BTC to another wallet because of issues with fees

### ISSUE THREAD

**Issue by plus-x** [blockstack/blockstack-browser#1175]
**Description** 
This issue is related to [this wallet issue](https://github.com/blockstack/blockstack-browser/issues/1174)

When trying to send my available BTC balance to another wallet, I am confronted with an error message (not enough funds available).

- First, I have enough funds.
- Next, notice the fee is WAY too high
- Also, there’s no message saying whether or not I have to subtract the fee manually. Shouldn’t the wallet just send the bitcoin for me and deduct the fee automatically? It’s a complete UX nightmare to force the user to subtract the fee from the total amount and send the subtracted total manually!
- Finally, the amounts in the error message are displayed with the first leading 0.00... truncated. This looks very strange.

**Notes**

Check [current fee from API](https://bitcoinfees.21.co/api/v1/fees/recommended)
Fee value is about 500 today, which should be multiplied by the block size of 250B (correct?), which results in a value of 125,000 satoshis. (Again, is this correct?)

My calculation seems accurate since 125,000 satoshis comes to about $12, which is the same as Coinbase's current fee.

**System Info**

- Mac OS X 10.13.2
- Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)
- Blockstack version 0.22.1 (installed from official installer package)
- Also tested on earlier Blockstack versions

**Steps to reproduce:**

1. With latest Blockstack installed, launch it fresh
2. Go to your wallet via the menubar icon
3. The web browser should open at URL: http://localhost:8888/wallet/receive#coreAPIPassword=off&logServerPort=off
4. Try to send available BTC to another wallet
5. Behold the error message. Screenshots below

![xfer-1](https://user-images.githubusercontent.com/6692678/35078165-fe716c2c-fc11-11e7-804d-8cd792c3c8b4.png)

![xfer-2](https://user-images.githubusercontent.com/6692678/35078167-fe909c46-fc11-11e7-9f3b-f86b01eee924.png)

**Comment by larrysalibra** [comment]
Thanks so much for the detailed bug report @plus-x !

> Finally, the amounts in the error message are displayed with the first leading 0.00... truncated. This looks very strange.

Totally agree. The current transaction generation method passes through error messages from core which deals with satoshis. We're in the process of migrating away from that.


>  It’s a complete UX nightmare to force the user to subtract the fee from the total amount and send the subtracted total manually!

Agree here as well! We have lots of room to improve.

> Next, notice the fee is WAY too high

Your wallet has 3 unspent transaction outputs, so sending money out means you're making a transaction with 3 inputs.
https://utxo.blockstack.org/insight-api/addr/17xzDqGt9y2WNwZMNq6182E1BsEdN8N9kR/utxo

We tend high on fees so that transactions go through quickly. Based on this, the fee calculation looks pretty close to accurate to me. 

Below is from this tool: https://estimatefee.com

<img width="1172" alt="screen shot 2018-01-18 at 6 45 48 pm" src="https://user-images.githubusercontent.com/597182/35094383-0d6a48de-fc80-11e7-8769-971300f12851.png">


> First, I have enough funds.

I think what may be happening is that core's transaction generating is refusing to generate a transaction with dust. Tagging @kantai who might have a better idea. 

Either way, I agree with you that it is not acceptable that we don't give users clear and actionable feedback as to what is happening and what they can do about it.

Thank you again for your detailed feedback - should have some more answers for you soon!

**Comment by plus-x** [comment]
Thanks for the response!

What does this actually mean? "Your wallet has 3 unspent transaction outputs..."

How does this occur?

Is there any way to lower the fee, any tricks?

I'll wait for your further response as to how to even get this money out of my wallet.

Thanks!

**Comment by kantai** [comment]
> What does this actually mean? "Your wallet has 3 unspent transaction outputs..."
> How does this occur?

Every time you make a bitcoin transaction, the leftover amount creates a new "unspent transaction output" for your wallet. In order to transfer _all_ of your funds out of your wallet, you need to use all of those old leftover amounts. However, this increases the size of the transaction, and therefore the fee.

> Is there any way to lower the fee, any tricks?

Currently, our wallet software _doesn't_ support altering your fees manually. 

However if you _really_ want to send low-fee transactions to get the funds out, you _can_ use other wallet software to transfer out of the address. It is possible to use your recovery phrase to access the BTC address -- the wallet software must support importing a BIP39 seed, and the derivation path is the standard `/44/0/0`. You can do this in Electrum, for example, by creating a new wallet and selecting "I already have a seed phrase", entering your recovery phrase, going to options and ticking "BIP39".

![seed-phrase-electrum](https://user-images.githubusercontent.com/1153552/35161293-bddcf76a-fd0d-11e7-8be1-d021451ce522.png)

**Comment by wbobeirne** [comment]
Closing as the above comment provides a workaround.
