### ISSUE TITLE
Chrome doesn't load browser when a chrome update is pending

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1185]
I ran into this issue today and wanted to document in case someone else runs into it:

When a chrome update on macOS has downloaded and is pending install, opening the Blockstack Browser from the mac app gives you a blank chrome window with no page visible. 

It's not just a blockstack problem, any app calling the default browser open function results in a blank page being opened in chrome.

Making this as wontfix since it isn't a problem on blockstack's side.

Moving to a native solution would solve this.

**Comment by bionicDan** [comment]
I ran into this issue myself as well, and only determined the cause after finding the issue documented here.

Since the issue itself is out of our control, suggest preventing the failure from happening _silently_ from the user's perspective. Possible solutions (feasibility not yet determined) indicating the issue in the browser window itself, indicating the issue in the Mac's Blockstack menu bar item or documenting the potential for this behavior in the installation instructions.

**Comment by wbobeirne** [comment]
Now that it's a native app, this issue shouldn't persist.
