### ISSUE TITLE
Username capitalized in emails

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1395]
My username "larry9.personal-test.id" is capitalized in emails - valid usernames aren't allowed to have capital letters.
<img width="1031" alt="screen shot 2018-05-25 at 11 08 46 pm" src="https://user-images.githubusercontent.com/597182/40551970-f84bd9e0-6070-11e8-8d78-962091f78608.png">

**Comment by larrysalibra** [comment]
Still seeing this problem: 
<img width="871" alt="screen shot 2018-06-18 at 6 18 17 pm" src="https://user-images.githubusercontent.com/597182/41530862-05574b2c-7324-11e8-8b45-febe1dfa7f09.png">
<img width="924" alt="screen shot 2018-06-18 at 6 18 26 pm" src="https://user-images.githubusercontent.com/597182/41530864-067115d8-7324-11e8-9621-1870f2960052.png">

**Comment by larrysalibra** [comment]
This issue is fixed for me on desktop but happens still if i register via mobile:

<img width="898" alt="screen shot 2018-06-27 at 12 37 41 am" src="https://user-images.githubusercontent.com/597182/41943194-cf83fd3a-79a2-11e8-9271-e1c74d378d81.png">

**Comment by aulneau** [comment]
Are you testing this on my pr branch? It has not been merged yet.

**Comment by larrysalibra** [comment]
i'm just using https://browser.blockstack.org

**Comment by Mike-EEE** [comment]
FWIW this issue is responsible for a nasty situation that I have gotten myself into with my own name:
https://forum.blockstack.org/t/cannot-register-username/5634/

Also, it would seem that the `-` [is allowed](https://github.com/blockstack/blockstack-core/blob/feature/docs-bns/docs/blockstack_naming_service.md#registering-bns-names), but when I attempted to use this for my name during registration, it provides a message saying that it is _not_ allowed, so it would be nice to perhaps have this addressed as well.

Everything else here has been super awesome, though.  Very inspiring material and vision here. 👍

**Comment by wbobeirne** [comment]
This has since been resolved. Sorry for the inconvenience.
