### ISSUE TITLE
Incorrectly verifying recovery key feedback not visible on mobile

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1423]
After incorrectly verifying the secret recovery key, the words on the button change to "Try again" to indicate that the user should try again.

The words on the button aren't visible on mobile because the user's finger typically blocks it.

This leads to confusion as to what is happening.

Video: https://drive.google.com/file/d/1MPSbJH5bp5y0Ehhlhult0t2eKcBcq86T/view?usp=sharing

Suggest adding feedback elsewhere on the screen.

**Comment by aulneau** [comment]
I don't know if I agree with the logic that 'the users finger typically blocks it', I don't think users will keep their finger on that button for so long that they cannot see the text change. I think ultimately what would be great is to have a notifications system in place where we can send a notification that says 'Sorry, please try again'.

I opted for updating the copy in the button because we have such limited real estate on mobile already, adding in any kind of content in the main area of the screen could cause the main action 'Continue || Try again' to fall below the fold. In addition to the copy change, the other things to denote an updated state are: the selection is dismissed, the words are rearranged, and the words you have to select change.
