### ISSUE TITLE
Blockstack auth logo color is reversed and looks weird/broken/bad

### ISSUE THREAD

**Issue by cuevasm** [blockstack/blockstack-browser#1457]
When logging in with the browser on Windows to the forum, this is what I see. I don't know if this is on the forum side or the browser side, but it should probably be updated to a logo you can see against white. 

![auth](https://user-images.githubusercontent.com/6131188/41124804-f1a7b294-6a57-11e8-8e28-d64e6766e69e.PNG)

**Comment by larrysalibra** [comment]
@cuevasm this is an issue with the browser - the logo is set by the forum:  - the discouse-blockstack plugin uses the "logo_small" logo: https://github.com/blockstack/discourse-blockstack/blob/master/plugin.rb#L33

The problem is that this is displayed on purple on the forum and white in the browser. One way to fix this is to add an additional configuration option to discourse-blockstack plugin. I've opened an issue over there: https://github.com/blockstack/discourse-blockstack/issues/4

Another option is to change the logo and style on the browser in a way that works. Happy to add you as admin on the forum if you want to play with this.

**Comment by larrysalibra** [comment]
Thank you for reporting @cuevasm ! :-D

**Comment by wbobeirne** [comment]
The logo now has a less prominent placement during auth, and doesn't look as weird, so I think this isn't really an issue anymore.
