### ISSUE TITLE
Do we need Flow?

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack-browser#1484]
Half of the project is using flow, the other half is not. I wonder if we should remove the flow tests (as they add a great amount of time in circle ci.

Are we getting any benefit from using flow on only half of the project? My vote is to remove it and if we want to have this project typed, then we should discuss if Flow is the best way to do it (vs something like TypeScript).

cc @yknl @larrysalibra @hstove

**Comment by hstove** [comment]
We also use Flow in blockstack.js, and I think Gaia as well? So there is some standardization there. Personally, I'm a fan, especially because of how it's built to be used with React. Nothing against TS here, but if the only downside is that it adds a bit of time to CI deployment, I don't think it's worth removing. Especially since the browser is getting bigger and bigger, my thought is that we should use Flow more often. It's a small hurdle during development, but adds to maintainability.

Just my 2 cents

**Comment by yknl** [comment]
The idea was that we would gradually add Flow into the entire code base as we work on older parts and when we add new code. I'm in the camp of continuing to do that, but we will need to be more disciplined. I'm not against Typescript, but it would be a very time consuming endeavour at this point and the benefits doesn't justify it.

**Comment by aulneau** [comment]
cool! sounds good to me! I think I fixed the speed issues I referenced, too.

**Comment by larrysalibra** [comment]
+1 to what @yknl said. We just made more progress on the other libraries (which have either smaller codebases or were written from scratch) adding flow and have been good at catching any issues in code review.
