### ISSUE TITLE
Design and info tweaks to grant access screen

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1545]
<img width="410" alt="screen shot 2018-07-22 at 1 52 26 pm" src="https://user-images.githubusercontent.com/767828/43048497-9c17ba54-8db6-11e8-9ab8-4413bdc335f6.png">

**Comment by wbobeirne** [comment]
Just some clarifications:

* What's the behavior of the back button? Send them to the homepage of the requesting app, or the previous page?
* What's the behavior of cancel? Same as back button, or just close the modal and stay on the browser page?
* Should it this full height even with one ID, or size itself based on number of IDs with a max height where it becomes scrollable?
* Should it cut off the last ID to indicate it's scrollable if there are more than ~3 IDs?

**Comment by moxiegirl** [comment]
I have two primary ids none of which yet have secondary.  That made this confusing. This button only shows secondary IDs is that correct?  So, if I have none...then _Select an ID to use_ is not valid for that _primary_.    So maybe don't display that sentence if the user has no primaries.

Combining the id selection with the arrow to take the continue action is just generally confusing.  Why not make the two functions distinct --- and it would match the visual language we use on other dialogs.

**Comment by jeffdomke** [comment]
The only changes are in the text (no buttons, or other UI elements). Text changes and URL.

**Comment by wbobeirne** [comment]
So I started to implement this, and realized that implemented as-is would give users a false sense of security. Right now the URL we have is provided in the manifest.json as `start_url`. This is completely developer defined, and not at all asserted. I discovered this when authing from helloblockstack.com:

<img width="320" alt="screen shot 2018-08-06 at 3 46 12 pm" src="https://user-images.githubusercontent.com/649992/43737910-dd1b1056-9990-11e8-83be-1c961ac7d327.png">

Note that someone left it as `localhost:5000`. What this means is that, as of right now, any app can claim to come from any domain. If the purpose of adding this was purely for disambiguation, then it's fine as-is. But if we're doing this for security purposes, this'll have to come after a change to blockstack.js that asserts that the manifest URL matches `start_url`, or provide an additional field like `manifest_url` that we can display instead.

@jeffdomke thoughts?

**Comment by jeffdomke** [comment]
That is a serious bummer. I wonder how this was originally conceived. Suppose it was a big assumption on my part that security was the goal. I don't think there is too much disambiguation utility. @larrysalibra @yknl maybe weigh in. If they don't have a strong argument otherwise, I would suggest we just ditch that part.

**Comment by wbobeirne** [comment]
> That's not true, we do verify the app domain.

We _do_ verify that the app request and manifest are hosted on the same domain. We _don't_ verify that the manifest file's `start_url` key matches the domain, which is all we get out of blockstack.js. We don't expose the requesting app's domain or manifest domain, so we can't use that without making changes to blockstack.js or re-decoding the auth request.

**Comment by wbobeirne** [comment]
I realized that I could use the domain from the encoded auth token directly, so I'm doing that. However, I think that adds yet another item that browser does that should be a part of blockstack.js, but we're already doing other things with the decoded auth token, so ¯\_(ツ)_/¯. Opened #1580.

**Comment by larrysalibra** [comment]
> We don't verify that the manifest file's start_url key matches that domain, which is all we get out of > blockstack.js.
* We haven't ever used the `start_url` - it's part of the progressive web app manifest standard that isn't actually used in blockstack auth. It's in example manifest.json files because it was there in the first hello blockstack app. Doing some research on it it, this field is only allowed to be a relative URL https://developer.mozilla.org/en-US/docs/Web/Manifest#start_url

* What's the behavior of the back button? Send them to the homepage of the requesting app, or the previous page?

Originally it was P]previous page - which was the homepage of the requesting app until the new on-boarding process shipped

* What's the behavior of cancel? Same as back button, or just close the modal and stay on the browser page?

Cancel left them in the browser before, but should probably send them back.

> We do verify that the app request and manifest are hosted on the same domain. We don't verify that the manifest file's start_url key matches that domain, which is all we get out of blockstack.js. We don't expose the requesting app's domain or manifest domain, so we can't use that without making changes to blockstack.js or re-decoding the auth request.

Please open feature requests and/or submit pull requests.

> I realized that I could use the domain from the encoded auth token directly, so I'm doing that. However, I think that adds yet another item that browser does that should be a part of blockstack.js, but we're already doing other things with the decoded auth token, so ¯\_(ツ)_/¯. 

The authenticator should never have to do anything with the auth tokens, it would be great if you could propose an API in an issue on blockstack.js that provides the information and functionality the authenticator needs.

**Comment by markmhx** [comment]
I'm closing this issue since it's rather old now and @wbobeirne appeared to address its essence with this merged PR: https://github.com/blockstack/blockstack-browser/pull/1580

@moxiegirl has also created a new issue to address possible confusion with this modal's dual purpose: https://github.com/blockstack/blockstack-browser/issues/1866

Please open other separate issues if any more needs discussed here aren't already captured elsewhere.
