### ISSUE TITLE
Make clear auth screen have more roadblocks and warnings

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1566]
It seems very dangerous to me to allow app developers to prompt the user to erase their browser.

I encountered this in the iOS SDK:

https://github.com/blockstack/blockstack-ios/issues/36

In that instance, the app developer hooked up this functionality to a sign out button and I clicked it thinking it would let me sign out. If i didn't carefully read the prompt that appeared, my credentials would have been gone.

In this case, it was a misunderstanding that resulted in this functionality being used in an app this way, but it makes it pretty clear how someone nefarious could create an app that causes problems for users.

<img width="412" alt="screen shot 2018-08-03 at 2 55 40 pm" src="https://user-images.githubusercontent.com/597182/43629000-802bd97a-972e-11e8-8f7f-ac11e98dc1b9.png">
<img width="422" alt="screen shot 2018-08-03 at 2 55 50 pm" src="https://user-images.githubusercontent.com/597182/43629002-820c8334-972e-11e8-9d0f-30ad9a4211ac.png">
<img width="417" alt="screen shot 2018-08-03 at 2 55 58 pm" src="https://user-images.githubusercontent.com/597182/43629005-83f5a996-972e-11e8-96b8-2fcd4d6d0c9e.png">

**Comment by yknl** [comment]
@larrysalibra agreed that this could cause problems for users. But we need some way to reset the browser from within apps. Since SFAuthenticationSession browser windows do not share cookies/storage with the Safari app or SafariViewController, if the browser were to get into a bad state, there is no way for the user to reset it. This has happened a few times already and users were stuck with a blank screen every time they tried to sign in with Blockstack. Maybe this functionality should be separate from sign out.

The coming iOS 12 should help with this problem though because the auth session window will be able to share cookies/storage with the Safari app. So the user can reset state through it.

**Comment by shreyasthiagaraj** [comment]
Yep--this is why this was done in the first place.

"This has happened a few times already and users were stuck with a blank screen every time they tried to sign in with Blockstack."
Couldn't this be handled from the browser side? This kind of error state shouldn't exist no matter what is in local storage. If we find ourselves in this state, could we not offer the option right there to clear the browser and restart?

**Comment by wbobeirne** [comment]
Closed via #1581.
