### ISSUE TITLE
Research testing processes and come up with a testing script.

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#1575]

**Comment by wbobeirne** [comment]
Just dumping my personal experiences here

### Automated Cross Browser Testing

In general, this stuff is extremely brittle and requires a ton of effort from engineers to maintain its functionality. However, it can catch a bunch of useful stuff once well tuned. Some options I've had limited experience with:

* https://www.seleniumhq.org/
* https://www.cypress.io/ 

### Headless Browser Testing

Much easier to develop, keep up to date, and run are headless browser tests. However, typically only works for Chromium or Firefox since it's something the browser has to build support for.

* Traditionally I'd used PhantomJS or SpookyJS, but both projects have since dropped maintenance. I don't know what the hot newness is here.

### Cross Browser Smoke Testing

Often a good starting point, simply load a few things in every browser and make sure it doesn't explode. It doesn't capture most (or really any) of our complicated workflows, such as authentication, but it's better than nothing.

We can also get our mocha tests to run in each browser, which ensures that all browsers support the APIs we leverage, and the babel-transpiled code. And you basically get it for free, since we already have a bunch of tests.

* https://mochajs.org/#running-mocha-in-the-browser run in BrowserStack or SauceLabs

### Testing Scripts

Regardless of whether it's manual or automated, we should have human-language scripts to be either implementation specs, or guides for people to read on how to test features. Many projects have these, but I personally helped work on [MyCrypto's Workflow Checklists](https://github.com/MyCryptoHQ/MyCrypto/wiki/Workflow-Checklists) which are pretty comprehensive, especially for some of the really niche smart contract features.

**Comment by aulneau** [comment]
I haven't used it personally, but have heard very positive things about cypress.io

**Comment by markmhx** [comment]
@zone117x is this issue still relevant given your recent work on testing?

**Comment by zone117x** [comment]
I'd consider this closed
