### ISSUE TITLE
Save password modal blocks Stealthy button. 

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1726]
![Screen Shot 2018-11-20 at 8:17 PM](http://marker.screenshots.prod.s3.amazonaws.com/1549f7a302d04dfb86d5181801f935b2-1542745026923.png)

Think we can block this behavior? Or maybe detect when it triggers? Open to other ideas. When user sees this very high likelihood they will get frustrated by the seed steps. 

This example is stealthy native app: 
4.5.2566
SAMSUNG-SM-G930A
samsung
26801
android
8.0.0

---
### More Info

**Source URL**: [file:///Users/jeffdomke/Desktop/Screen%20Shot%202018-11-20%20at%203.14.20%20PM.png](file:///Users/jeffdomke/Desktop/Screen%20Shot%202018-11-20%20at%203.14.20%20PM.png)

**Comment by jeffdomke** [comment]
Yeah, I get that. But we need some solution or option here. This is tanking UX for this particular users. Can we detect and then change how we display button?

**Comment by aulneau** [comment]
I don't think we'd be able to detect it. I think the way we should be framing the options is rather than trying to detect or change native browser functionality, we should just try to work on a change in design that isn't so heavily affected by this behavior.

there are possibly options related to changing the field so that it's not a 'password' type, that would prevent the save password thing from showing, but that would be a hack that I don't recommend. 

Moving away from the password itself could solve this.

**Comment by jeffdomke** [comment]
We can swap the position of that statement and the button. 

"Moving away from the password" = if your knee hurts, just chop off your leg. Problem solved 👌

**Comment by moxiegirl** [comment]
Just a thought, I had a tester use our onboarding this weekend. And, despite being a Blockchain, follower he had problems with our onboarding.

Our "password" is not a password in the general sense, that is, for an account. It is a session password or a browser instance password.

- We should not call it a password.  **Session key**
* We should ask parts of their key phrase -- this reups the importance of that phrase. We need only store the sequence we asked from them and ask it again. enter words 2/5/4) or something?

**Comment by markmhx** [comment]
I'm closing this issue out in favor of a newer one here: https://github.com/blockstack/blockstack-browser/issues/1817
