### ISSUE TITLE
trying to use clear-auth url, button does nothing

### ISSUE THREAD

**Issue by thaonguyenle** [blockstack/blockstack-browser#1789]
on a mac, on chrome
went to this URL: https://browser.blockstack.org/clear-auth
Pressed the red: push this button to confirm, it does nothing. 

<img width="1031" alt="screen shot 2019-01-11 at 2 57 19 pm" src="https://user-images.githubusercontent.com/39015059/51056624-4a36a280-15b1-11e9-9752-2ea5a77eabc4.png">

**Comment by GInxh** [comment]
Try the new updated browser, and let me know if you still haver these new issues.

**Comment by hstove** [comment]
Hey TN, sorry we didn't follow up on this issue.

It turns out that there has been some miscommunication, and this `/clear-auth` URL was never meant to be visited directly. It's only there for mobile apps to use in a specific way.

We've updated our 'update the browser' prompt to allow you to reset your browser from that page, so you should never be able to get 'stuck'.

I'm going to close this issue, as we've decided to leave this page as-is, and not tell people to go to this URL.
