### ISSUE TITLE
New onboarding flow with optional email and seed education screens

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1820]
This updated design combines all the learning from user testing rounds in the fall. 

– The sequence is reordered so that all users see their seed before deciding to email themselves, and can skip that step. 
– It also contains revised language: 'Secret Key' and 'Secret Key Backup' 
– The seed verification prompts the user to tap all words.
– The referring app is featured prominently in the first screen to help not get disoriented. 

![Frame 2.png](https://images.zenhubusercontent.com/5c01542d2c4f4d3a813340fc/474908d2-ff13-44e4-8e5e-8d74575944b3)

Details in figma.

**Comment by markmhx** [comment]
This design looks generally promising. A few initial thoughts:

- Should we change the name "Secret Key" to "passphrase" like Lisk? Or would perhaps a different name better convey what's new and familiar about it at the same time (e.g. "multi-word password")?
- Might users be less confused during sign-in if prompted for just the secret key as a primary input, relegating the backup code to a secondary option (since it's "backup" after all)? Inputs that ask for "this or that" tend to confuse me personally since they make me doubt what I should provide to move forward, even if both would work in my case.
- Should we warn users that their password can never be reset or sent to them if forgotten? We have such strong warning language for the secret key and the password may also benefit from it as well.
- Do we have any data that suggests that users forget their password less than their secret keys? It seems to me that the email+password route is predicated essentially on the idea that passwords won't be lost as easily. But I wonder if that's indeed the case if users are being forced to persist their secret keys with the selective-word confirmation screen. If it's not the case, then I'd question needing to support the email+password route at all.

Since this design is similar in many ways to Lisk's onboarding flow, I'll post the analysis of Lisk here when ready so we have the opportunity to update this design with its learnings. And if you have a link to the Figma handy, I might try my hand at updating a version with those learnings.

**Comment by markmhx** [comment]
Here's a link to the Lisk analysis as it pertains to this design proposal: https://paper.dropbox.com/doc/Lisk-registration-and-sign-in-analysis--AW7aJjmLmCyPk7CrFfxLovU6Ag-D6sZ7ighQ0JXtSfIGiTmG

**Comment by jeffdomke** [comment]
- I don't think we've tested "passphrase" but we have a few other words. Secret Key is what 1password uses. It also seems to make sense since the name instructs you what it is and how it should be treated. But, I can't say with 100% certainty it is better. 

- "secret key as a primary input" Agreed. 

- "Should we warn users that their password can never be reset" Sure, we did previously and we removed but I can't remember the rational. 

- "suggests that users forget their password less than their secret keys" No data, but it seems nobody is actually remembering their seed. So I think you're asking what is the actual performance of that recovery method, or how often do people just forget their password and fail silently with both methods? We don't know. Related side note: When we tested the option to "send" or "save" their key someplace with options all the testers wanted it sent to their email :)
