### ISSUE TITLE
Remove apps 

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1881]
I had dinner with a Blockstack fan last night that tried out Blockstack again over the weekend and came away with impression that the apps are the same as they were ~1 year ago.

This doesn't reflect well on the project.

I think that the list of apps in the browser should be removed since they're not being updated.

**Comment by markmhx** [comment]
We recently redesigned the homepage to ensure that the apps are dynamically loaded and up-to-date.

The change will be included in the next release: https://github.com/blockstack/blockstack-browser/pull/1823

I'm closing this issue out as a result, since I think we've addressed this concern. But please re-open if you think we should still remove apps entirely for some other reason.
