### ISSUE TITLE
Remove paid IDs, deprecate wallet and add site-wide deprecation banner

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-browser#2005]
It will become technically impossible for users to purchase IDs using BTC once we make the switch to Stacks v2 in mainnet. 

As such, we need to remove that capability from the Blockstack Browser beforehand. And since the wallet exists only to fund BTC-based ID purchases, we should remove the ability to receive more funds and add a notice that informs users of its deprecation and encourages withdrawals.

We're currently working on software that will replace the Blockstack Browser entirely. However, it won't likely be both ready for general release nor supportive of paid ID purchases by the time Stacks v2 goes live. As such, we will start directing all users interested in paid ID purchases from that point onwards to use the CLI.

@moxiegirl can provide copy for the notices below:

<img width="803" alt="Screen Shot 2019-12-19 at 14 15 53" src="https://user-images.githubusercontent.com/28991/71176894-148f4480-226b-11ea-8146-1d2fe8aa8c52.png">
<img width="743" alt="Screen Shot 2019-12-19 at 14 16 04" src="https://user-images.githubusercontent.com/28991/71176896-148f4480-226b-11ea-88e5-3f903a8961c0.png">

**Comment by moxiegirl** [comment]
@markmhx so, it looks like here by "withdraw" funds you mean they should send the funds back to a bitcoin account. Is that correct?

**Comment by markmhx** [comment]
Yep that's correct

**Comment by moxiegirl** [comment]
Text suggested:

Blockstack no longer supports name purchases and renewals through the explorer. To purchase names, please [use the Blockstack command line interface](https://docs.blockstack.com). If you have Bitcoin (BTC) funds in the explorer, [transfer them out](https://blockstack.browser.com).

@markmhx we have examples in the cli but I think we need a page that shows how to buy and renew a name in the docs.  The link above should go to that article rather than the cli.

https://github.com/blockstack/blockstack-core/issues/1212

**Comment by markmhx** [comment]
I'm expanding the scope here a bit to include a site-wide deprecation banner such as the following mockup, with "the Stacks Wallet" linked to https://wallet.stacks.org

<img width="1127" alt="Screen Shot 2021-01-07 at 18 32 28" src="https://user-images.githubusercontent.com/28991/103925020-329a4200-5117-11eb-93ac-129cc4a4dc5d.png">
