### ISSUE TITLE
Username registration errors

### ISSUE THREAD

**Issue by ryanarndtcm** [blockstack/blockstack-browser#2029]
This is coming in from a user in support who has been sent a link to this issue to add to. I will add anything else in here that they send to support.

Email 1

>Hello, I can’t seem to register a new username to my account even though it’s available.The message I’m getting when trying to register a new username: "entaxyuser" on the blockchain:

>Sorry, it looks like the blockchain failed to process your name registration. Please contact us at support@blockstack.org for help. Some apps may be unusable until you register an ID.

>Could you please advise on next steps.
----------
Email 2

>I am trying to follow the instructions in the recovery email to recover my blockstack user: "entaxy_user.id.blockstack", but it’s not working.

>When I enter my password trying to recover it, I get an error saying "bad header; couldn't find a good version (got 4207965993)"

>Could you please let me know what I can do to recover that username from the email I received ?

**Comment by kamalsaleh2** [comment]
Hello Ryan, 

Thank you for the reply. 

I can no longer reproduce the issues in either of the emails. My guess is that it took some time to synchronize because I can now see my username

1- I managed to register "entaxyuser.id.blockstack" but it hasn't showed up yet, on my account which I'm guessing is what happened to the other one.

2- The blockstack ID "entaxy_user.id.blockstack" was recovered and I can now see it with my other user.

Thank you so much for looking into it. 

Cheers !
