### ISSUE TITLE
Authentication protocol questions

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#411]
This is an issue to track outstanding authentication questions that devs might want to know answers to when evaluating our platform.

* What do devs do when users transfer their name to another address? 
* What happens when multiple names are owned by the same address?
* What’s the log in before download method that actually works?
* How does versioning work? (That’s to say, when there are breaking changes in the protocol, how do the various parts in the system know this?)
* In the event of a blockchain migration, what happens to DIDs?

I created this issue here so that we can work it into our weekly sprints.

**Comment by jcnelson** [comment]
> What do devs do when users transfer their name to another address?

Should be fine.  Core knows which address owns which name.

> What happens when multiple names are owned by the same address?

On sign-in, the user should be prompted with a list of names (i.e. all the names the Portal owner address owns).

> What’s the log in before download method that actually works?

Sign in with a persistent address, I thought?

> How does versioning work? (That’s to say, when there are breaking changes in the protocol, how do the various parts in the system know this?)

Right now, all API calls are prefixed with `/v1/`.  Any changes to an API call will be prefixed with a successive version number (`/v2/`, `/v3/`, etc.)   We will keep backwards compatibility for as long as we can (indefinitely unless noted otherwise).

I expect that developers will be free to mix and match API call versions, and that API calls may have the same names but change versions.  For example, an application should be able to do something like call `GET /v1/names/judecn.id` and `GET /v2/blockchains/bitcoin/consensus` without breaking.

> In the event of a blockchain migration, what happens to DIDs?

If we switch blockchains, then Core will index the first blockchain, and then the second blockchain, and then the third blockchain, and so on.  We retain copies of the chain state for the blockchains we use, so that if any of the blockchains ever disappear, we can (1) simply ship the chain-derived state with the Core node and (2) serve the archived chain state to users who want to verify that their Core's chain-derived state is consistent with the legacy chain state.

**Comment by wbobeirne** [comment]
Closing as stale.
