### ISSUE TITLE
Running on por X but api calls point to another port Y --> v0.6.2 macOS

### ISSUE THREAD

**Issue by yeradis** [blockstack/blockstack-browser#414]
Just installed the macOS v0.6.2

But there are things that doesn't work, like Wallet

My instance is running on port 8888, but when inspecting calls (chrome, opera) i see that some calls fails, like those related to walled, they are calling a different port 6270
And there is nothing, at first, i thought i was my firewall, but after disabling it and trying again, got the same result.

When checking settings i can see there http://localhost:8888/account/api
that the configured port is 6270, no sign of 8888 (i can reach the portal at this one)

**Comment by muneeb-ali** [comment]
@yeradis thanks for reporting! Port 6270 is an API port for Blockstack Core and if you do

> ps -A | grep blockstack

You'll see a process similar to:

> .virtualenvs/core/bin/python2 -m blockstack_client.rpc_runner start 6270

that should be listening on 6270

This looks like some other issue. I can also confirm the issue on macOS v10.12.4 and Blockstack v0.6.2. The wallet keeps saying: 

> Loading address...

I debugged the issue and looks like the API daemon is up because: 

> http://localhost:6270/v1/names/muneeb.id 

works but

> http://localhost:6270/v1/wallet/payment_address

doesn't work. Which makes me think that it's an API credentials issue. 

@larrysalibra or @shea256 can help with this.

**Comment by muneeb-ali** [comment]
@yeradis please double-check that you don't have an earlier version of the Blockstack CLI installed. [Here](https://github.com/blockstack/blockstack-portal/issues/415#issuecomment-294387339) is a thread that can help.

**Comment by yeradis** [comment]
@muneeb-ali just the first time using blockstack, downloaded the installer from here, no previous version

**Comment by jackzampolin** [comment]
Closing as stale.
