### ISSUE TITLE
Wallet is not loading a bitcoin address

### ISSUE THREAD

**Issue by john-light** [blockstack/blockstack-browser#425]
I opened the wallet to deposit bitcoin and it is not loading a bitcoin address.  

v0.6.2  
macOS  

![screen shot 2017-04-18 at 11 30 28 am](https://cloud.githubusercontent.com/assets/9424721/25146950/a2dd0c0a-242a-11e7-8770-1b79764c69a4.png)

**Comment by NathanTheGr8** [comment]
same on v0.6.2 MacOS 10.12.4

**Comment by NathanTheGr8** [comment]
works as of 0.7.0 yesterday

**Comment by larrysalibra** [comment]
@john-light thanks for the bug report. v0.6.2 has issues starting core which is why your wallet address isn't appearing.

We've resolved some of those issues on v0.7.0, as @NathanTheGr8 has so kindly noted. Some users (including @shea256) are still having problems on their machines. @jcnelson and I are working on fixing the problem. Thank you so much for your patience and feedback!

**Comment by dominictarr** [comment]
I'm also observing this problem on 0.7.0, running on linux, with default non-local blockstack-core

**Comment by larrysalibra** [comment]
@john-light @dominictarr This was the result of Blockstack Core stability issues on macOS. @kantai fixed most of those, so this shouldn't be an issue on v0.9.0. Please let us know if it is.
Thank you again for reporting it!
