### ISSUE TITLE
ability to open blockstack automatically when you log in (macOS Login Items)

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#579]
It would be extremely helpful to add a Blockstack Preferences Pane that would automatically add "able to open automatically when you log in" located in macOS `System Preferences / Users & Groups/ User / Login Items`.

<img width="299" alt="screenshot 2017-06-30 08 33 55" src="https://user-images.githubusercontent.com/1711854/27735798-554ead8a-5d6f-11e7-8d9c-6b938b1543dd.png">
<img width="667" alt="screenshot 2017-06-30 08 34 18" src="https://user-images.githubusercontent.com/1711854/27735799-555420b2-5d6f-11e7-812b-73f92907f83e.png">

**Comment by larrysalibra** [comment]
Great idea @guylepage3 !

**Comment by larrysalibra** [comment]
For an initial implementation of this feature, we'd like to make it so that the Blockstack macOS app configures itself on first one to start automatically when the user logs into their macOS account. 

When quitting blockstack we should add a check box option that allows users to disable the start on log in functionality:

<img width="427" alt="screen shot 2017-08-11 at 12 32 51 am" src="https://user-images.githubusercontent.com/597182/29181178-c8120050-7e2c-11e7-8314-a4501e76f4ef.png">

We can modify the above dialog to include a checkbox option "Start Blockstack on login" in a similar to the dialog below:

<img width="427" alt="screen shot 2017-08-11 at 12 33 07 am" src="https://user-images.githubusercontent.com/597182/29181239-f790e3aa-7e2c-11e7-8520-b631ba929e3a.png">

When starting Blockstack on log in, the macOS app should **not** automatically open the user's web browser.

**Comment by shea256** [comment]
> When starting Blockstack on log in, the macOS app should not automatically open the user's web browser.

Good call on this.

**Comment by larrysalibra** [comment]
Thanks to @yknl this is complete and will be shipped in the next release!

**Comment by guylepage3** [comment]
Awesome! Thanks @yknl 😄
