### ISSUE TITLE
Run browser in native app window

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#599]
Create a proof of concept of mac app with browser running in native app window

**Comment by larrysalibra** [comment]
I've made a build with the browser running in a native app window as a proof of concept. 

It's tagged: [v0.11.3-alpha.3](https://github.com/blockstack/blockstack-browser/releases/tag/v0.11.0-alpha.3) and in branch: https://github.com/blockstack/blockstack-browser/tree/v0.11-webkit

<img width="917" alt="screen shot 2017-07-07 at 2 07 55 am" src="https://user-images.githubusercontent.com/597182/27925966-41d79998-62b9-11e7-8c93-6b85dbb7b8e2.png">

Sign ins still currently only work with default browser. Additional changes are needed to support that.

The javascript is still being served from localhost. We'd need to make some changes to the javascript app to support running from a `file:///`

Thoughts on native app window versus in web browser?

**Comment by guylepage3** [comment]
Well.. this was great to see live because I did not react how I thought I would. 

There seemed to be something off about the native app when I launched it. I thought I'd enjoy the experience better but the fact that there was no "browser" navigation items and no address bar really threw me off.

1. I like that I'm viewing the new internet in my own window but it's missing the browser. I don't feel so good about not having browser navigation.
2. How would we force developers to build in navigation? Right now we are "highly" recommending developers to apply the "Blockstack Status Bar" into their application but we cannot guarantee that they will.
3. How will we get the user to jump from the native app, log in to a Blockstack App, then jump them back to Blockstack. The feeling is off for me.

I'm very surprised by playing around with the native app and how odd it feels. I totally thought it would be a better experience but I am disappointed.

**Comment by pstan26** [comment]
Used for a second, then clicked `Hello Blockstack` and got shut out of the native app and couldn't reopen it. Thought it was neat, and maybe some UI upgrades (like a nav bar + wallet balance) and UX upgrades (sign-in without using the browser), along with adding some more badass apps could create a great experience. To keep focus on addressing some of @guylepage3's comments:

> I like that I'm viewing the new internet in my own window but it's missing the browser. I don't feel so good about not having browser navigation.
Probably need some reasoning to support this. 

> How would we force developers to build in navigation? Right now we are "highly" recommending developers to apply the "Blockstack Status Bar" into their application but we cannot guarantee that they will.
We could simply control which apps are displayed as we are the gatekeeper for app discovery at the moment. Only apps that allow backbars + status to be listed -- this is a thing we are going to have a hard time enforcing in the long run unless we create a really great onboarding experience. Apple had the iPhone as a physical piece of hardware to enforce lock-in into their app store, whereas we don't have the luxury. This is a point in favor of leveraging the user's default browser (in favor of this as people can make themselves adn their apps discoverable on the legacy web)  or creating our own browser.

> How will we get the user to jump from the native app, log in to a Blockstack App, then jump them back to Blockstack. The feeling is off for me.
Agreed. Would you say that the experience is only slightly better in-browser though?

**Comment by guylepage3** [comment]
@larrysalibra are we pushing this issue off for this sprint?

**Comment by larrysalibra** [comment]
Yes

**Comment by jackzampolin** [comment]
Closing as stale.

**Comment by larrysalibra** [comment]
Not stale. We're still doing this, just after the token distribution.

It's already working in this branch: https://github.com/blockstack/blockstack-browser/tree/feature/native-webkit

**Comment by wbobeirne** [comment]
OK, now I think this is _actually_ stale.
