### ISSUE TITLE
Storage doesn't work without username

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#609]

**Comment by kantai** [comment]
See https://github.com/kantai/blockstack-storage-js/tree/aarons-hacked-up-storage for progress on this.

**Comment by shea256** [comment]
Ha cool, look forward to seeing this in action.

**Comment by kantai** [comment]
Now merged into blockstack-storage-js master.

**Comment by larrysalibra** [comment]
As we discussed in the call:

My understanding is that users who add a name to a profile after using storage with a "throwaway" account will lose access to the data they stored.

I'd envision typical user flow to be something like this:

Mary sees a CoolApp built on blockstack and wants to try it out. She installs blockstack, a profile is automatically created and she starts using CoolApp. Mary decides that she really likes CoolApp and the new internet and wants to have her own name, so adds username to her profile.


In this case, Mary would be confused and unhappy if the data she'd created in CoolApp disappeared as soon as she spent money to add a username to her profile.

@kantai How hard is it to change storage so that users don't lose access to data after adding a username to their profile?

**Comment by kantai** [comment]
I believe right now, they actually won't lose storage (tested it in regtest). This is because storage logically separates a path `path` from other paths like `/datastore/data-pubkey/path`, and the `datastore` and `data-pubkey` actually don't change between the throw-away and the registered name. The blockchain_id is only used as a hint when the data-pubkey isn't given.

@jcnelson will have to confirm that this is correct, though, as I'm still working my way through a complete understanding of Gaia.

**Comment by jcnelson** [comment]
That is correct.  `data-pubkey` and `datastore` are derived from the application's origin and the name owner key passed in by Portal.  As long as the application's origin and the user's master private key don't change, all of the datastore routing information will be persistent.

**Comment by larrysalibra** [comment]
This is fixed and shipped in v0.11.1
