### ISSUE TITLE
Implement new on-boarding flow

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#618]
See design in #534

**Comment by larrysalibra** [comment]
@guylepage3 @shea256 i've done a rough implementation of the on-boarding flow based on the designs in #534 and our discussions.

Among the the things aren't done yet:

1. the 12 word phrase is hardcoded (fake) until we switch to 12 words (see #605) 
2. the verifying your identity key page doesn't do anything (click continue to skip it)
3. the email notification form doesn't do anything 

Per our discussions, there's no progress indicator/navigation component. I'll add that in after @guylepage3 designs it.

A couple of notes:

* People should have the option of opting out of email collection, so I added a `skip` option to the email notifications page. 
* We'll need to add in a "download backup" page as well if it's decided we're going with it.

Now is a good time for your feedback regarding the flow, wording, etc.

**Comment by larrysalibra** [comment]
Forgot to mention, the new on-boarding flow is available in this branch: https://github.com/blockstack/blockstack-browser/tree/v0.12-new-onboarding

**Comment by shea256** [comment]
OK awesome @larrysalibra I'll jump in shortly.

**Comment by guylepage3** [comment]
@larrysalibra @shea256, just went through the process and have a few comments..

1. First 3 welcome screens seem fine.. Personally I never read only the first one whenever I sign up for anything with a Welcome screen. I value my time to much to read them. Which correlates to... Less screens equates to a better sign up process for me.
2. There needs to be more emphasis on the importance of remembering the password as it's something that the user will only enter one or two times in the lifetime of the profile. Very easy to forget this.
<img width="573" alt="screenshot 2017-07-14 15 34 17" src="https://user-images.githubusercontent.com/1711854/28227994-8c2cc77e-68aa-11e7-89fe-a8dd3f837b88.png">
3. There needs to be a "Back" button here so that the user can go back and write down their identity key
<img width="480" alt="screenshot 2017-07-14 15 41 25" src="https://user-images.githubusercontent.com/1711854/28228096-fe775538-68aa-11e7-9d5d-cdc9071fcc46.png">

**Comment by larrysalibra** [comment]
@guylepage3 @shea256 

I forgot to commit changes to the password page & order of screens last night.

Just did that in https://github.com/blockstack/blockstack-browser/commit/99ac6632f1feb1d8a03ff0f9f1843d7ef04f7366

The major change is that selecting a password happens before seeing your identity key.

> There needs to be more emphasis on the importance of remembering the password as it's something that the user will only enter one or two times in the lifetime of the profile. Very easy to forget this.

Yes. Do we want to add a password confirmation field as well?  #604 

> There needs to be a "Back" button here so that the user can go back and write down their identity key

Agreed. I can add a link "show me the identity again" or something to that effect that lets users go back.

**Comment by guylepage3** [comment]
>Yes. Do we want to add a password confirmation field as well? #604

I feel that it is wise. Shows emphasis on how important it is and allows us to communicate importance on the confirmation page.

**Comment by guylepage3** [comment]
>Agreed. I can add a link "show me the identity again" or something to that effect that lets users go back.

Let's just use the work "back" for now. Simple is better until we get feedback.

**Comment by larrysalibra** [comment]
We have a couple remaining implementation tasks that I've split off into separate issues:
#645 
#648 

Otherwise on-boarding is implemented and works!

**Comment by shea256** [comment]
Hell yeah!
