### ISSUE TITLE
Add a photo uploading tool to the editor page

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#65]

**Comment by shea256** [comment]
@larrysalibra You took a crack at this right? How's this been coming along?

**Comment by larrysalibra** [comment]
@shea256 We need to refactor the s3 upload stuff so that it accepts images - right now it expects JSON. This should be pretty straight forward using knox and uploading to the user-provided S3 bucket. 

For the blockstack provided storage, will the upload API endpoint accept binary files or only JSON? -> https://github.com/blockstack/blockstack-browser/blob/1cd23eff3ea2e2adde847c4ba36c9da1fcf8564d/app/js/utils/s3-utils.js#L21

**Comment by larrysalibra** [comment]
Self-hosted S3 issues: #139 and blockstack upload API accepting non-binary files (see previous comment) are blocking this.

**Comment by larrysalibra** [comment]
This works with Dropbox hosting. Waiting on API for Blockstack provided hosting. See #143
