### ISSUE TITLE
Account restoration doesn't work.

### ISSUE THREAD

**Issue by jay-ithiel** [blockstack/blockstack-browser#676]
Restoring an account doesn't restore a profile but creates a new profile without a username.
Made a quick youtube video running through the restoration process: 
[blockstack account restoration](https://www.youtube.com/watch?v=narIdbQIHyk&feature=youtu.be)

The video was made using browser v12, but the issue persists in v13 as well

**Comment by larrysalibra** [comment]
@jay-hwang thanks for your help reporting this. 

Account restoration will be fixed in the next release. Please not that it only restores the first profile. If you had more than one name, you'll have to click "create profile" to generate the additional addresses.

I've opened an issue to improve on this in the future #729.

Please let me know if you have any problems restoring your account!

**Comment by larrysalibra** [comment]
We have two account restoration flows. One from the welcome screen and one from the settings screens. The latter doesn't work properly.

**Comment by larrysalibra** [comment]
I'm simplifying our account restoration flow so that you can only restore an account from the on-boarding screen. If you have an existing account, you have to erase your account from the browser and the restore from the on-boarding screen. This is similar to how other things work. For example, on iPhone, if you want to restore your phone, you first erase it and then restore from the on-boarding screen.

**Comment by jackzampolin** [comment]
This fix has been included in the latest release. Closing.
