### ISSUE TITLE
Deployment on windows

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#719]
We want a reasonably easy way to deploy the browser + core on Windows that is deliverable in a tight timeline.

We also want a longer term solution as to how to package and deploy the browser on desktop and mobile.

**Comment by larrysalibra** [comment]
After discussing this with @kantai and @jackzampolin, we came to the conclusion that docker is the only realistic way to get the browser and core easily running on windows in a short period of time.

@jackzampolin already has core and the browser working well in docker.

There are a few missing components to make it completely functional and user friendly:

- [ ] Add support for `blockstack:` protocol handler: #325 
- [ ] Create an easy to use installer

**Comment by kantai** [comment]
There's a couple of things that are not great about the docker solution that are making me more hesitant than I was before.

First, Docker comes in 2 flavors on Windows: Docker Toolbox and Docker 
* "Docker" is their recommended approach, but it only runs on Windows Professional or Enterprise and certain hardware, because it requires Windows HyperV
* Docker Toolbox installs Virtualbox and uses *that* to run a bootToDocker image -- not the greatest thing in the world, but their installer is open source and gets things mostly set up correctly.

So, in order to support most Windows users, we'd want to use the docker toolbox approach -- this isn't *too* terrible, but it can get a little wonky. Anyways -- one potential approach is to fork their installer repo, and add a script to the installer that downloads the latest blockstack docker image and adds a `launcher`-like script.

**Comment by jackzampolin** [comment]
@kantai `boot2docker` is pretty rough on end users especially if they are not comfortable in virtualization environments. But we can hopefully hide most of that from them. How well supported/up to date is the OSS `b2d` stuff? Do you have a link?

**Comment by kantai** [comment]
I believe the `b2d` stuff is pretty up to date. I think even the HyperV approach uses `b2d`, so there's no real getting around it if we ship via docker. We should be able to hide most of the nastiness from users.

**Comment by jackzampolin** [comment]
This is shipped. Closing.
