### ISSUE TITLE
missing "back" button on on-boarding

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#777]
Missing "back" button on on-boarding. We used to have a "back" button here.

<img width="606" alt="screenshot 2017-09-15 08 17 00" src="https://user-images.githubusercontent.com/1711854/30482192-f5daab20-99ef-11e7-945d-f82842a0f507.png">

**Comment by yknl** [comment]
@guylepage3 
I’m not sure it’s a good idea to add a back button in the “Write down identity key” view. The preceding step is the " Choose a password” view (shown below), which upon submit generates the private key. 

![image](https://user-images.githubusercontent.com/29081231/30500623-307af266-9a2d-11e7-8478-7040ac34d883.png)

If we were to add a back button in the "Write down your identity key" view, the user would be taken back to the “Choose a password” prompt. They would need to re-enter a password and a new private key will be generated. It doesn't seem like a path that users would take.

Also, none of the preceding screens have a back button, so only have one here seems a bit odd. 

If you look at the next screen though, there is a back button. It makes sense here since the user might need to go back and actually write down their identity key.

![image](https://user-images.githubusercontent.com/29081231/30500644-50242f7e-9a2d-11e7-8020-bc60aab806b6.png)

Let me know your thoughts.

**Comment by guylepage3** [comment]
@yknl all valid points but the user needs to feel that there is an exit point at all times through on-boarding. If they do not they could feel lost and just quite the process altogether.

Also, some users will want to refresh their given backup phrase. by going back and then re-entering their password, they will receive a new backup phrase.

The pain of having to re-enter a password is less than the pain of being stuck in the on-boarding process.
