### ISSUE TITLE
update profile tab view to be clearer for the user

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#789]
I propose upgrading from this:

<img width="396" alt="screen shot 2017-09-18 at 12 16 41 am" src="https://user-images.githubusercontent.com/994646/30529081-a54b0320-9c07-11e7-8785-bb85a5374781.png">

To this:

<img width="467" alt="screen shot 2017-09-18 at 12 21 25 am" src="https://user-images.githubusercontent.com/994646/30529083-a8ba658c-9c07-11e7-9a6e-f7b36fb7b6d7.png">

**Comment by shea256** [comment]
This is meant to go from a page that's very confusing and hard to use to something that is more intuitive.

If you click edit, you should have context of where you are. With the blue highlight on current page that would solve the problem.

Also there should be those three buttons and that's it. Users can create new profiles in the "more" tab already. And we can figure out how to add back in "advanced" and "view publicly", maybe as an icon with a little drop down of additional actions. But we'll tackle that later and put it off.

**Comment by larrysalibra** [comment]
I've taken a stab at implementing what @guylepage3 @shea256 and I discussed above. Code is in the https://github.com/blockstack/blockstack-browser/tree/feature/redesign-profiles-improvement branch.

I added a button to create a new profile on the all profiles page since its original position is occupied by the "more" link.

Screenshots:
<img width="485" alt="screen shot 2017-09-18 at 4 56 01 pm" src="https://user-images.githubusercontent.com/597182/30537039-618a4bce-9c92-11e7-8c33-e36e772e3bfd.png">
<img width="484" alt="screen shot 2017-09-18 at 4 56 10 pm" src="https://user-images.githubusercontent.com/597182/30537042-645209be-9c92-11e7-9b15-35f5d8cca9b8.png">
<img width="484" alt="screen shot 2017-09-18 at 4 56 15 pm" src="https://user-images.githubusercontent.com/597182/30537044-669ba2fc-9c92-11e7-923d-f8ad2e6cce01.png">
<img width="477" alt="screen shot 2017-09-18 at 4 56 24 pm" src="https://user-images.githubusercontent.com/597182/30537051-696a4308-9c92-11e7-9420-d5808cb385a7.png">

**Comment by larrysalibra** [comment]
I also tried another approach -> making the secondary navigation "move" so that the currently selected view is highlighted and the center. I also tried changing the copy to use "Blockchain ID" terminology instead of profiles. "IDs" doesn't work very well because of our all caps style, but that's something we could work on.

Code is in https://github.com/blockstack/blockstack-browser/tree/feature/redesign-profiles-improvement-alternate 

<img width="482" alt="screen shot 2017-09-18 at 5 01 01 pm" src="https://user-images.githubusercontent.com/597182/30537226-0f0bd2e0-9c93-11e7-8e71-b04cd15dc427.png">
<img width="483" alt="screen shot 2017-09-18 at 5 01 08 pm" src="https://user-images.githubusercontent.com/597182/30537229-115823aa-9c93-11e7-9c02-e9b29fda16e7.png">
<img width="478" alt="screen shot 2017-09-18 at 5 01 19 pm" src="https://user-images.githubusercontent.com/597182/30537232-139254f6-9c93-11e7-9f4f-875944182739.png">
<img width="466" alt="screen shot 2017-09-18 at 5 01 36 pm" src="https://user-images.githubusercontent.com/597182/30537234-166e3cbc-9c93-11e7-9211-146fc9398ac9.png">

**Comment by larrysalibra** [comment]
I think we can further simplify the "all profiles" view as well, by removing some of the potential navigation paths.

Right now, clicking on a profile card takes you to the edit profile page. This is confusing in that it looks exactly the same as editing your current profile, but you're getting there from a different route.

I propose we change the "clicking the card" function to setting the default profile or user's "current ID" instead of editing the profile. We could then remove the links that currently exist for setting the default profile. We could indicate the default profile visually with some sort of perhaps by a badge, some sort of outline color.

Thoughts?

**Comment by guylepage3** [comment]
This is great guys.. thanks for the feedback. We had proposed this in the original designs but then decided to keep the verbiage that we currently have.

Will update at some point today. 😄

**Comment by larrysalibra** [comment]
@guylepage3 @yknl and I had a sync up and decided: 
* to go with @shea256's original version https://github.com/blockstack/blockstack-browser/tree/feature/redesign-profiles-improvement because the moving secondary navigation items in the alternate version feel like they're jumping around.
* to simplify navigation by change the function of clicking on the id cards from navigating to the id to setting the id as the current id
* to update copy in the browser to use blockchain id and id instead of profile or avatar.

**Comment by shea256** [comment]
ok awesome nice work guys

**Comment by larrysalibra** [comment]
I've made these changes and merged into `feature/redesign`
