### ISSUE TITLE
Re-enable advanced functions page

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#845]
See #790 for some design notes.

As part of re-enabling the advanced pages we'll need to switch to using the browser payment key. See the work done on: #730

**Comment by larrysalibra** [comment]
The advanced functions pages are zone file update and transfer.

**Comment by guylepage3** [comment]
Are we going to throw this back in settings?

**Comment by larrysalibra** [comment]
@guylepage3 I was planning to add them to the ellipse menu that shows the transfer from onename option since these are per - blockstack-id settings - for the moment. (these will only appear if there is a username)

**Comment by guylepage3** [comment]
I see. That seems a bit complex and difficult to find from a user's perspective. We should ensure a setting button is always available so that the user can discover it. I look at one of my favorite apps, Spotify, and they keep their settings discoverable at all times for the user.

<img width="253" alt="screenshot 2017-11-22 16 08 11" src="https://user-images.githubusercontent.com/1711854/33149947-921c21dc-cf9f-11e7-967e-3653b5ea4588.png">
<img width="417" alt="screenshot 2017-11-22 16 08 43" src="https://user-images.githubusercontent.com/1711854/33149949-9226987e-cf9f-11e7-890b-bc7b953b7bb8.png">
