### ISSUE TITLE
Add support for manual update of zone files

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#88]

**Comment by larrysalibra** [comment]
@shea256 is this meant to be an advanced feature for people who want to point their zonefile to a profile not hosted on S3? 

Or simply a feature to update the zonefile when someone chooses to use their own s3 credentials instead of blockstack s3?

**Comment by shea256** [comment]
@larrysalibra Yes, this is meant to be an advanced feature. We can hold off on this for now.

I'm also going to write up something on the restructuring of the app that I can send over to you shortly.

**Comment by shea256** [comment]
Moving this feature to the next release (`v0.3.0-alpha`).

**Comment by larrysalibra** [comment]
We need this feature for self-hosting. With the ability to update the profile URL in the zone file, we can only self host photos.

**Comment by larrysalibra** [comment]
We'll provide a feature that lets users manually update their zone file using the newly implemented core update api call that takes an owner key: https://github.com/blockstack/blockstack-core/issues/538 https://github.com/blockstack/blockstack-core/pull/543

**Comment by larrysalibra** [comment]
<img width="622" alt="screen shot 2017-08-24 at 2 16 40 am" src="https://user-images.githubusercontent.com/597182/29631464-4cfce740-8872-11e7-9941-5b23a4138624.png">
<img width="689" alt="screen shot 2017-08-24 at 2 16 29 am" src="https://user-images.githubusercontent.com/597182/29631465-4f0f0f54-8872-11e7-8607-56fa1956c506.png">

This is completed and available by clicking on a profile that has a username and then the zone file button.

**Comment by shea256** [comment]
Some quick feedback on this @larrysalibra. I would get rid of the placeholder text. And I would also tuck this option under an advanced section. Many users will get confused by a button that says "zone file".

**Comment by larrysalibra** [comment]
> And I would also tuck this option under an advanced section. Many users will get confused by a button that says "zone file".

Agree. I'll change the button name to Advanced for now. We're doing the redesign this sprint and advanced settings for names should go in a less prominent location.

>  I would get rid of the placeholder text

That's not placeholder text, it's the current zone file text. It's there so that users can easily edit it. For example, if they want to change the location of the profile, they can replace the URL in quotes instead of having to write a new one from scratch.

The text in the `textarea` is grayed out when it's not in focus because that's the style all of our `input` elements have. (See the API settings page for an example). Agree it looks misleading. Assume it is something we will address in the redesign.
