### ISSUE TITLE
Include a trust level badge in the profile

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#892]
Design:
![image](https://user-images.githubusercontent.com/29081231/31518935-bf1941ac-af6e-11e7-881c-708d5bf667da.png)

**Comment by shea256** [comment]
OK here's my feedback

1. The un-verified social accounts still don't emphasize to me that I shouldn't trust them. Larry shared some screenshots from Keybase and right now they do a better job at this.
1. If the +1 stars are confusing on the view screen then we have a few options: (a) only show them on the edit screen as an enticement for when you're editing your profile (b) allow the ones on the view screen to have different clicking behavior from the rest of the row so that they take you to the edit profile view
1. Get rid of "untrusted" and just make it "trust level: 0" so that it's consistent with when the trust level goes to 1, 2, etc.

**Comment by yknl** [comment]
> The un-verified social accounts still don't emphasize to me that I shouldn't trust them. Larry shared some screenshots from Keybase and right now they do a better job at this.

Some options for this:
![image](https://user-images.githubusercontent.com/29081231/31529584-1f5461b2-afa8-11e7-848c-38e66cce0262.png)

![image](https://user-images.githubusercontent.com/29081231/31529579-175556f6-afa8-11e7-8e8f-0f7d07b5fec2.png)

**Comment by guylepage3** [comment]
I like the 2nd one @ken. Clear communication.

**Comment by shea256** [comment]
Just had a discussion with @guylepage3 and @pstan26 about this and now thinking we might want to change "trust level 2" to "verified accounts: 2".

The reason is that "trust level" might not be clear enough to people. We don't ever want someone to have to think "what is a trust level?".

It serves us well to use language in labels that is as close as possible to the actual data that underlies it.

In this case, we're saying that this user actually has 2 verified accounts.

@yknl @larrysalibra let me know what you think.

**Comment by larrysalibra** [comment]
The problem with "verified accounts: 2" that is that you lose the aspirational aspect of `trust level` - it makes me want to "level up" or be higher than someone else.

Verified accounts doesn't do that for me. Having said that, it is more clear.

It seems silly to tell people have many verified accounts they have - they can see that from their profile.

Besides being aspirational & competitive, the main reason for having a "trust level" is that you need to be higher than a certain level to do certain things.

**Comment by shea256** [comment]
Hm there's a conundrum here. Thinking more about this 🤔

**Comment by guylepage3** [comment]
Ok. Another idea...

What if we eliminate the annoyance of the Verification Confirmation process altogether by having Blockstack pay for the user's name if they complete 3 of any account confirmations. 

1. This will eliminate the need for an annoying verification confirmation banner
2. It allows for hyper growth as more verifications will be completed
3. Allows us to use the "verified account number" as a badge that sits next to the user's profile image. Where ever the user's profile pic appears, their badge appears with them. If the user verify's 15 accounts the color behind the number changes. If they verify ALL possible accounts, they are rewarded with a special "verified" badge

Thoughts?

**Comment by guylepage3** [comment]
![browser-macos-40a-profile-verified-d18 2x](https://user-images.githubusercontent.com/1711854/31564159-d62f257a-b02f-11e7-9c2d-0278da61efad.png)

**Comment by shea256** [comment]
I would just keep it the way we have it and then we can revisit next week if need be. For now, let's not worry about checking up on the date of the account creation. Worst case we simply rely upon ID verification via photo ID upload.

**Comment by guylepage3** [comment]
<img width="400" alt="browser-macos-40b-profile-verified-d18 2x" src="https://user-images.githubusercontent.com/1711854/31564751-1e7d1d80-b032-11e7-9413-6e6e1a622eb4.png">

<img width="400" alt="browser-macos-40c-profile-verified-special-d18 2x" src="https://user-images.githubusercontent.com/1711854/31564752-1e8d94c6-b032-11e7-89bd-a9932e81a8d0.png">

**Comment by guylepage3** [comment]
@yknl after seeing my design a bit more.. i would like to move the "trust" badge up, below the profile image as it allows for better balance on the screen.

**Comment by guylepage3** [comment]
complete
