### ISSUE TITLE
User testing report - Oct 13

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-browser#915]
Mr. Haider

*Installation*: put the link at the top otherwise it sends you straight into issues for the browser!! On Github

*Password*: you can go with 5 or maybe even less characters, thats too few and there is no rules for char count 
*Making a profile*:  Not clear to anyone that they should go on and make a profile..no direction to do so
*Social verification*: Pull the instructions section to above the “Proof URL” section
- Not clear you need to copy URL from the tweet modal
- No UI feedback as it is validating
- Can’t save proof validation
- Just copy the Onename process and do it soon!
*Open Blockstack*: Once you close the browser, if you don’t add it to applications folder on Mac it won’t show in finder. Maybe add an arrow in the background of the window to drag into applications folder

cc @yknl  @larrysalibra @guylepage3 @shea256

**Comment by pstan26** [comment]
Mr. Ricker

- Call it a "Recovery Phrase" instead of a key
- "Default Storage" is a phrase that makes you reluctantly choose it...at least put a "?" button that opens up more info on what this is
- Create Profile, again, is not clearly indicated and therefor when you first sign up it feels like you have created a profile.

cc @yknl @larrysalibra @guylepage3 @shea256

**Comment by shea256** [comment]
# User testing report

## On-boarding process

### Password input on-boarding page

**Problem:** The word "key" in "identity key" was confusing because a key is something physical that let's you get into a house. For those who understand what digital keys are, it doesn't look like a key, so this would have to be explained.
**Solution:** Change “identity key” to something that uses “phrase” in lieu of “key”. This wording should indicate that it’s for account recovery. This could be “recovery phrase,” for example.

### Email input on-boarding page

**Problem:** Users often skip the email input field because they don't want to receive notifications and that is the only current reason given for entering one's email address. The email address can seem like an afterthought but entering it actually will bring a lot of user value.
**Solution 1:** Change the email address input page so it says “Enter your email address” and then have checkmarks for (a) “get account security notifications” (b) “join the blockstack mailing list”
**Solution 2:** Move the email address page before the password

### Storage selection on-boarding page

**Problem:** The “Connect Dropbox” and “Connect IPFS” have a pointer cursor when you mouse over them (the hand icon). This confuses users because it seems like the buttons are clickable.
**Solution:** Change the button cursor type.

**Problem:** The “choose your storage provider” on-boarding panel flickers after you choose default storage.
**Solution:** Remove the flickering.

**Problem:** People are sometimes confused by what default storage means. They wonder where the data is being stored and are confused by the fact that we earlier told them that they are in control of their storage. If we're storing their data on a server somewhere, we need to explain to them why they're in control. It's because their data is signed and encrypted and eventually will be replicable across multiple cloud storage hubs. Which means data tampering and decryption and censorship are all invalid attack vectors. 
**Solution:** Put a tooltip next to the “use default storage” button that explains what “default storage” is. Explain in this tooltip that their computer encrypts and signs all their data before backing it up to a server in the cloud. For simplicity, we connect them with a reliable server to provide the backups and online access. In the future, more will be available and they will be able to choose from multiple vendors across multiple geographies. Something like this.

### On-boarding completion

**Problem:** Users may forget they ever created a Blockstack account but we want them to have some historical experience with us. If they ever forget they signed up with Blockstack, we want them to be able to search their email and see an email about Blockstack and say "oh so I did sign up with this service." This would be evidence their past self is providing to their future self.
**Solution:** Send the user a welcome email as soon as they create an account

## Profile Tab

### Profile viewing

**Problem:** When the user goes to the profile page, he first clicks "add a username" and doesn't notice the edit panel.
**Solution:** Move the “add a username” from the “view profile” page to the “edit profile” page.

**Problem:** When the user goes to the profile page, the user doesn't have a feeling that this profile is theirs.
**Solution:** Add both name input and photo upload to the on-boarding process.

**Problem:** The bitcoin address on the profile is confusing for users. They think it's a Bitcoin address for payments and they don't know that the address is really the address that owns and secures their identity.
**Solution:** Consider using “ID-“ as the prefix for the identity address. This might be clearer than "b-".

**Problem:** When you read the trust level tooltip, it says "by verifying your social proofs". When I first read this I was a bit confused. The proofs aren't being verified. Rather the accounts are being verified using proofs.
**Solution:** Change the language in the trust level tooltip to say “Increase your trust level by verifying your social accounts”

### Profile editing

**Problem:** The verification instructions are currently incredibly confusing. This is the part that every user has the most trouble with. They typically go first to enter a username and then go to the "proof URL" field and then are either confused about what to do or they enter the URL to their profile there. They may then notice the instructions below but they have already been confused and wasted their time. Then, once they go to the instructions, they sometimes create the post but then they don't know what to do next. They're looking for where they should paste the proof URL. Then, once they have pasted the proof URL, they are trying to figure out how they can close the view or save the information.
**Solution:** Update the verification instructions to mirror the process we have developed for the Onename product. Order the components as follows: (1) Enter your username (2) Verification button or post creation instructions (3) Field for proof URL (4) Save/Close button.

**Problem:** Users don't know what to do when they are told to create a GitHub gist. They will often click to open the window but then they don't know what to type in the title field and the body field.
**Solution:** Change the instructions for GitHub from "Create a public gist with the following text." to the following steps: (1) "Copy the text below" / text field with verification text (2) Button: "Create a Gist" (3) "Paste the text in the description and body, then click 'create public gist'" (4) Copy the URL of the Gist and paste in the field below.

**Problem:** Profile viewing and editing is not clear to people.
**Solution:** Consider merging the “view profile” and “edit profile” pages

**Problem:** If you click anywhere in the “increase your trust level” bar outside of the text box, nothing happens.
**Solution:** Make sure the full bar is clickable (instead of just the text).

## Settings Tab

**Problem:** The "backup account" view in the settings panel has different wording than the rest of the app.
**Solution:** In the “backup account” settings panel, replace “backup phrase” with “recovery phrase”

**Comment by shea256** [comment]
It's actually pretty incredible when you watch someone first complete the Twitter verification process in the browser and then do the same process in the Onename app.

With the browser, the user is pretty confused but then in Onename the user goes right to it.

This is a good lesson for us to mimic the Onename process in the browser. There was a lot of sweat and user testing that originally went in to that and we're re-learning all the lessons :)

## Browser screenshot

<img width="780" alt="screen shot 2017-10-14 at 1 42 37 am" src="https://user-images.githubusercontent.com/994646/31573036-488abc00-b081-11e7-9304-9f5aa6ae5817.png">

## Onename screenshot

<img width="612" alt="screen shot 2017-10-14 at 1 42 25 am" src="https://user-images.githubusercontent.com/994646/31573038-51e556de-b081-11e7-91a3-37133a69e724.png">

**Comment by larrysalibra** [comment]
# verification input color 

I find the color of our current verifications confusing. I keep trying to click in the white space and typing in it - not sure why the input boxes are gray. 

# auto saving 

Auto-saving of profiles is counter intuitive.

Users expect to be able to edit things without consequence and cancel their edits if they decide not save them. We’re publishing for the world to see whatever they type in those boxes without even an option to cancel.

**Comment by shea256** [comment]
+1 on both Larry. The color is a bit confusing and could be better. Also the auto-saving could be changed to something like what we have on the modals on Onename. So long as it's a simple change. The save button at the bottom of every verification window would be very helpful in any case to give the user an action to "complete" the verification process.

**Comment by guylepage3** [comment]
https://github.com/blockstack/blockstack-browser/issues/915#issuecomment-336612201

Whoa. this drastically changed somewhere along the line from design to execution. By changing the verification process from "blue" to standard colors, i would skip this completely. I would not know that it's special. with onename i know it's special because it's a pop-up. on mobile usually a stark color change or new screen helps the user identify that it's a special screen and they need to execute it. I would not have recommended that visual queue of all the same color and would like to see it changed back to the blue format

**Comment by shea256** [comment]
Nice to have: password strength indicator.

**Comment by wbobeirne** [comment]
Closing as stale, the browser has changed a lot since this was made. If there are any good pieces of feedback that should still be acted upon, we should open them as separate individual tickets.
