### ISSUE TITLE
Add password strength indicator

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#919]
Use this: https://github.com/dropbox/zxcvbn

**Comment by jdlee022** [comment]
I'd love to pick this up if you'd like to point me in the right direction. I'm looking to make my first open source contribution and I have a serious interest in Blockstack. I went through the dropbox github link you posted and I think I can make it happen.

**Comment by larrysalibra** [comment]
@jdlee022 Awesome!

The password fields where this should be added are in two places:

https://github.com/blockstack/blockstack-browser/blob/master/app/js/welcome/components/EnterPasswordView.js

https://github.com/blockstack/blockstack-browser/blob/master/app/js/welcome/components/RestoreView.js

Let me know if you have any questions

**Comment by jdlee022** [comment]
@larrysalibra it took me a while because I had to make arrangements to upgrade to macOS Sierra to run the browser, but I've got it working. Two questions though: (1) should I comment my code? I noticed the rest of the files weren't commented, (2) should I make it so that the user can only submit the password if it has a strength score of 3+? The zxcvbn library scores are represented as 0: too guessable, 1: very guessable, 2: somewhat guessable, 3: safely unguessable, 4: very unguessable.

**Comment by maxkreja** [comment]
I just wondered why you are using a switch-condition when returning the different colors. You could just go with and if-block and check for values greater or smaller instead of evaluating every single strength-level  like this:

```JavaScript
// Instead of this:
displayPasswordStrength() {
    switch (this.state.pwStrength) {
        case 0:
        case 1:
        case 2:
            return <p className="label-red">The password you entered is too weak</p>
        case 3:
            return <p className="label-amber">The password you entered is average</p>
        case 4:
            return <p className="label-green">The password you entered is strong</p>
        default:
            return null
        }
    }

// Do this
displayPasswordStrength() {
    if (this.state.pwStrength < 3)
        return <p className="label-red">The password you entered is too weak</p>
    else if (this.state.pwStrength === 3)
        return <p className="label-amber">The password you entered is average</p>
    else if (this.state.pwStrength > 3)
        return <p className="label-green">The password you entered is strong</p>
}
```

I think this is approach makes more sense because the user should see that his password is too weak already when his password reached level 1, not only when it is exactly 2.

**Comment by jdlee022** [comment]
@maxkreja the switch statement acts in the same way, displaying that the password is too weak when the score is a 1 or 0.

The if statement approach probably makes more sense intuitively and it takes up fewer lines of code so I will update it and resubmit the pull request later tonight.

While I'm at it do you see anything else that I should change?

**Comment by maxkreja** [comment]
@jdlee022 actually your are right, I forgot how switch statements work. There are no breaks or returns in for case 0 and 1 so it will go straight to case 2 I totally forget about this. 

I overlooked the code again and it seems fine as far as I can see. Great work, I hope they will merge your pull request soon.

**Comment by jmadd** [comment]
I'm new to open source and was looking for a way to contribute. This has been resolved by [this merge](https://github.com/blockstack/blockstack-browser/pull/1039) correct? Any reason this is still marked as "Open"?

**Comment by larrysalibra** [comment]
@jmadd thanks for noticing! It should be closed :-D
