### ISSUE TITLE
Improve the model for loading the key from the keychain

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#945]
Right now every time the user opens the app, the user is prompted for the password to decrypt the keychain key.

There are a few problems here:

1. This prompting wasn't there earlier and it can get very annoying.
2. The text that's shown doesn't accurately reflect what is happening. If anything, it should instruct the user to decrypt the password, rather than to update every single time.

<img width="453" alt="screen shot 2017-10-23 at 10 00 11 am" src="https://user-images.githubusercontent.com/994646/31893928-e0e7d6da-b7da-11e7-9378-10445190218a.png">

It seems like there should be a way to lean on the keychain and actually remove our dependence on password prompts.

**Comment by larrysalibra** [comment]
> rather than to update every single time.
This dialog should only display once after updating the browser.
There is a bug in the currently shipping version, v0.18.1 where it displays on each hard refresh of the browser. It was fixed in https://github.com/blockstack/blockstack-browser/issues/943

This dialog is not related to macOS keychain.

> The text that's shown doesn't accurately reflect what is happening. 

After the fix in #943 it should only display once after updating the browser if the state version has change.

Let me know if this clarifies the context.

**Comment by larrysalibra** [comment]
Please re-open if this is still an issue.
