### ISSUE TITLE
Update home screen to over-communicate on rather than over-promise on app readiness

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#952]
**Problem:** We don't want to over-promise on app readiness. We don't want to pretend like an app is ready to use when it's really not. By the same token, we don't want to not show people that various apps are in the works. 

**General solution:** We can address this problem by giving additional context around each application around how ready it is. One way to implement this is to split apps up into groups that indicate their level of development. This seems better than a label next to each application as users should be drawn to the user-ready apps first. These should be at the very top.

**Possible implementation A:**

One possible layout for this in the home screen would require doing away with this:

<img width="304" alt="screen shot 2017-10-24 at 12 47 34 am" src="https://user-images.githubusercontent.com/994646/31927135-adeebfba-b860-11e7-84f3-50738fa6fd77.png">

And instead implementing something like this:

```
User-ready Apps
---
[ICON] To Do List

Apps-in-progress
---
[ICON] Guild
[ICON] Ongaku Ryoho
[ICON] OpenBazaar
[ICON] Forum
[ICON] Casa
[ICON] Beacon
[ICON] Afia

Requests for Apps
---
[ICON] Encrypted Token Portfolio App
```

@guylepage3 @larrysalibra @yknl @pstan26 Let me know what you think. I think this addresses the problem in a nice and simple way. Maybe there's an even better way to do it.

**Comment by guylepage3** [comment]
@shea256 This is one option.. I feel it may not be significant enough of a change however and I don't see necessarily the value of providing written categories for the apps.

Is this a Home Screen or is it an App Store. I feel the Home Screen needs to come first.

I thought more about this last night/this morning and if we are going to remain in the browser rather than going the stand alone route then we should change the structure/layout of the browser. This structure/layout is made for mobile. It feels extremely awkward in the state that it’s in.

So i feel if we are going to remain in the browser we should adjust the layout accordingly.

----

A bit of a side note...

We could go back to the old structure.. nice beautiful and easy to use home screen with links in a top navbar. This provides a more traditional desktop experience. That with a simple 2 screen walk through would go a really really long way.

I personally wish we could provide the user with options..
1. Use a complete stand alone browser/app where we control everyting
2. Use the “plugin” and access the web via the browser of your choice

Somewhat like what 1Password does. As a user, I feel at this point that I would like to have both of these options.

I would love to just open an app that is Blockstack specific and access things there. Having the option would be nice. For myself, as a user, anyways.

**Comment by pstan26** [comment]
Think the high level problem to solve today for the token sale and until we
hit like 50 apps is context and expectation setting. By end of 2018 we will
have hundreds of apps (at that point it is no longer a home screen but an
app store that we code and curate -- a home screen will be curated by the
user and we don't offer that ability for the foreseeable future) and have
to categorize them, but that is not the problem to be solved today.

From user testing sessions we know that people have no clue what they are
looking at period... i.e. which apps work and to what degree, can you sign
in with your ID, can you store data to your storage, does the app itself
resolve to .id's, i the app single or multiplayer.

I think Ryan's second suggestion is the bare minimum with the most impact
and for that reason something we should use for the next few months:

User-ready Apps
---
[ICON] To Do List

Apps-in-progress
---
[ICON] Guild
[ICON] Ongaku Ryoho
[ICON] OpenBazaar
[ICON] Forum
[ICON] Casa
[ICON] Beacon
[ICON] Afia

Requests for Apps
---
[ICON] Encrypted Token Portfolio App

**Comment by shea256** [comment]
+1 @pstan26 - let's move forward with this structure.

**Comment by shea256** [comment]
@guylepage3 @larrysalibra @yknl let me know what you think the easiest way is to implement this.

**Comment by yknl** [comment]
+1 on implementing @shea256's suggestion, it should be fairly straight forward to implement

**Comment by guylepage3** [comment]
sounds good to me.

**Comment by shea256** [comment]
OK here's an ideal updated list:

```
User-ready Apps
---
[ICON] To Do List
[ICON] Forum

Apps-in-progress
---
[ICON] Guild
[ICON] Sampler (formerly Ongaku Ryoho)
[ICON] Casa
[ICON] Beacon
[ICON] Afia

Requests for Apps
---
[ICON] Encrypted Token Portfolio App
[ICON] Decentralized Microblogging
```

**Comment by guylepage3** [comment]
An alternative is we could go back to the old concept like this.. Ignore the visual..

But we could add "My Apps" back in and it clearly says "APPS". I don't think my dad would know what a User-ready App is. Nor would he care.

![dashboard-7](https://user-images.githubusercontent.com/1711854/32027797-ffbf9dce-b9b8-11e7-8206-b1c3bd1ebd44.png)

**Comment by shea256** [comment]
Ready to close?

**Comment by larrysalibra** [comment]
This shipped.
