### ISSUE TITLE
Consider changing the port number for the localhost server

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#978]
Unfortunately it is one of the defaults and conflicts with many projects.

Here's an example of a user who complained:

https://twitter.com/michaelzand/status/924191970263797760

Not sure what would go into this change and this isn't urgent but more something to think about in the future.

**Comment by Extreme1** [comment]
Would be great if this could change. Thx!

**Comment by larrysalibra** [comment]
The browser likely won't need to be served on localhost when we finish the move to native webview and this will no longer be an issue. 

In the short term, my apologies for the conflicting ports. I picked the number 8888 because 8 is good luck where I live: https://en.wikipedia.org/wiki/Chinese_Numerology#Eight

**Comment by guylepage3** [comment]
Haha.. ALL buildings in Vancouver are like this.. :)

![image](https://user-images.githubusercontent.com/1711854/32170138-d4f74490-bd49-11e7-91e8-c3c468c343ee.png)

**Comment by squio** [comment]
Can't run Blockstack (proxy) on my local dev machine (osx) which runs nginx on port 8888 for several dev projects. 

Is this configurable through the settings in `~/.blockstack/client.ini` or a command line switch? If not consider this for the next release please!

**Comment by rszrama** [comment]
8888 is the default port for MAMP as well.

**Comment by nottoseethesun** [comment]
Port `8888` is a total blocker for a lot of dev's these days.
