### ISSUE TITLE
how to reset password?

### ISSUE THREAD

**Issue by locomo** [blockstack/blockstack-browser#980]
I'm using Blockstack browser on macOS

I have my keychain phrase but neglected to store my password (thought it got stored in my password manager)

how can I reset my password?

**Comment by larrysalibra** [comment]
@locomo as long as you have your keychain phrase, you can restore your browser and create a new password.

**_Make sure you have your 12 word keychain phrase written down_** and then do the following:

1. Start with the Blockstack Browser displaying in Chrome (or your web browser of choice)
2. Open the Javascript console (i'm going to assume you know how to do this since you're posting on github)
3. Run `localStorage.clear()`
4. Close the tab with the browser.
5. Open the Browser again by selecting "Home" from the Blockstack icon in your menu bar.
6. Select the "Restore an existing keychain" option and follow the instructions.

**Comment by larrysalibra** [comment]
Let us know if you have any trouble or questions!

**Comment by locomo** [comment]
great .. that worked although pretty awkward for mainstream users.. is a 'reset password' option in the works?

**Comment by larrysalibra** [comment]
> great .. that worked although pretty awkward for mainstream users.. is a 'reset password' option in the works?

That's a great idea. Want to open an issue requesting that?

**Comment by locomo** [comment]
sure will do

**Comment by larrysalibra** [comment]
We've added a "reset browser" in #989 that enables this functionality without having to use the javascript console.
