### ISSUE TITLE
provide ui for password reset

### ISSUE THREAD

**Issue by locomo** [blockstack/blockstack-browser#981]
I recently installed the Blockstack app on macOS but neglected to record my password when doing the initial setup

I was able to reset my password but the process is cumbersome ( #980 )  and probably a turnoff for non-technical users.

Would it be possible to provide a user interface in settings to allow users to reset their password ?

**Comment by larrysalibra** [comment]
We've added a "reset browser" in #989 that users who have forgotten their password can also use to start from scratch with their keychain phrase. 

We can also consider adding a separate "reset password" option that essentially does the same thing with different language and preserving settings. 

Going to backlog this for now so that we can examine it again in the future.

Thanks again for bringing this to our attention @locomo !

**Comment by larrysalibra** [comment]
Closing this since our "reset browser" function has been serving as a way to reset password. We can reopen if this needs to be re-examined.
